#**Lab 9 - Iterative eigenvalues and Markov chains**

Enter your code in the spaces provided. Do not change any of the variable names or function names that are already provided for you. In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.

In [1]:
# Do not edit this cell.

LabID="Lab9"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

**Enter your name, section number, and BYU NetID**

In [2]:
# Enter your first and last names in between the quotation marks.

first_name="Brigham"

last_name="Andersen"

# Enter your Math 215 section number in between the quotation marks. 

section_number="001"  

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER! 

BYUNetID="abrigham"  

**Import NumPy**

In [3]:
import numpy as np

**Problem 1**

In [4]:
# This function approximates the dominant eigenvector of our matrix A.
A = np.array([[1,1],[2,0]])

def evect_approx1(x_0,k):
  x = x_0
  for i in range(k):
    x = np.matmul(A,x)
  
  return x

evect_approx1(np.array([1,9]),10)

array([3752, 3760])

**Problem 2**

In [5]:
# This function approximates the dominant eigenvalue of our matrix A.

def eval_approx1(x_0,k):
  x_k = evect_approx1(x_0,k)
  x_k1 = evect_approx1(x_0,k+1)
  return x_k1[0] / x_k[0]

eval_approx1(np.array([1,9]),10)

2.002132196162047

**Problem 3**

In [6]:
# This function approximates the dominant eigenvalue and eigenvector of our matrix A using the normalized iterative process.

def norm_evect_approx1(x_0,k):
  x = x_0
  for i in range(k):
    w = np.matmul(A,x)
    v = w[0] / x[0]
    x = w / np.linalg.norm(w)
  return x, v

norm_evect_approx1(np.array([1,9]),10)

(array([0.70635334, 0.70785942]), 1.995744680851064)

**Problem 4**

In [7]:
# This function approximates the dominant eigenvalue and eigenvector of an arbitrary matrix using the process described in Problem 4.

def norm_approx_gen(M,x_0,k):
  x = x_0
  for i in range(k):
    w = np.matmul(M,x)
    v = w[0] / x[0]
    x = w / np.max(np.abs(w))
  return x, v

norm_approx_gen(np.array([[2,4,6],[4,8,0],[1,2,9]]),np.array([1,5,-1]),10)

(array([0.98994349, 1.        , 0.98491523]), 12.01744017467949)

**Problem 5**

In [8]:
# This function approximates the dominant eigenvalue and eigenvector of an arbitrary matrix using the Rayleigh quotiend as described in Problem 5.

def ray_quotient(M,x_0,k):
  x_k = norm_approx_gen(M, x_0, k)[0]
  numerator = np.dot(np.matmul(M,x_k),x_k)
  denominator = np.dot(x_k,x_k)
  return numerator / denominator

ray_quotient(np.array([[2,4,6],[4,8,0],[1,2,9]]),np.array([1,5,-1]),10)

12.00149020429905

**Problem 6**

In [9]:
# Replace all of the 0 values with the vectors requested in Problem 6.
y = np.array([[3, 2, -2], [-1, 1, 4], [3, 2, -5]])
y_0 = np.array([1, 1, 1])

x_vect_3=norm_approx_gen(y, y_0, 3)[0]
print(x_vect_3)

x_vect_4=norm_approx_gen(y, y_0, 4)[0]
print(x_vect_4)

[ 0.36538462  1.         -0.61538462]
[ 0.70093458 -0.29595016  1.        ]


**Problem 7**

In [10]:
# This function returns the number of subscribers to the different streaming services after month k.

def subscriber_vals(x_0,k):
  x = x_0
  P = np.array([[0.7,0.2],[0.3, 0.8]])
  for i in range(k):
    x = np.matmul(P,x)

  return x

subscriber_vals(np.array([95,102]),10)

array([ 78.81582031, 118.18417969])

**Problem 8**

In [11]:
# Replace all of the 0 values with the value requested in Problem 8.
arr=np.array([0.6, 0.4])

netflix_subs6=subscriber_vals(arr, 6)[1]
netflix_subs6

0.596875

**Problem 9**

In [12]:
# Replace all of the 0 values with the matrix/vector/value requested in Problem 9.
to_a = np.array([0.8,0.5,0.3,0.2])
to_b = np.array([0.05,0.2,0.1,0.1])
to_c = np.array([0.1,0.1,0.3,0.1])
to_d = np.array([0.05,0.2,0.3,0.6])

trans_matrix=np.array([to_a,to_b,to_c,to_d])
trans_matrix

array([[0.8 , 0.5 , 0.3 , 0.2 ],
       [0.05, 0.2 , 0.1 , 0.1 ],
       [0.1 , 0.1 , 0.3 , 0.1 ],
       [0.05, 0.2 , 0.3 , 0.6 ]])

**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.   

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file. In the "File" menu select "Download .py". The resulting file can then be uploaded to http://www.math.byu.edu:30000 for grading.