#**Lab 5 - LU decompositions and Gaussian elimination**

Enter your code in the spaces provided. Do not change any of the variable names or function names that are already provided for you. In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.

In [1]:
# Do not edit this cell.

LabID="Lab5"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

**Enter your name, section number, and BYU NetID**

In [2]:
# Enter your first and last names in between the quotation marks.

first_name="Brigham"

last_name="Andersen"

# Enter your Math 215 section number in between the quotation marks. 

section_number="001"  

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER! 

BYUNetID="abrigham" 

**Import NumPy**

In [3]:
import numpy as np

**Problem 1**

In [4]:
def augment(A,b):
  aug_m = []
  for i in range(len(b)):
    row = np.append(A[i], b[i]).tolist()
    aug_m.append(row)
  return np.array(aug_m)

In [5]:
C=np.array([[3,2,1,1],[1,-2,1,1],[5,0,1,5]])
b=np.array([-1,3,2])
augment(C,b)

array([[ 3,  2,  1,  1, -1],
       [ 1, -2,  1,  1,  3],
       [ 5,  0,  1,  5,  2]])

**Problem 2**

In [6]:
def first_column_zeros(A):
  B=np.copy(A)
  for i in range(1, len(B)):
    B[i] = B[i] - (B[i,0] / B[0,0]) * B[0]
  return B

In [7]:
A=np.array([[2,1,3,1],[1,2,-1,2.5],[4,2,-1,1]])
first_column_zeros(A)

array([[ 2. ,  1. ,  3. ,  1. ],
       [ 0. ,  1.5, -2.5,  2. ],
       [ 0. ,  0. , -7. , -1. ]])

**Problem 3**

In [8]:
def row_echelon(A,b): 
  B = augment(A,b)
  for i in range(len(B)):
      B[i:,i:] = first_column_zeros(B[i:,i:])
  return B

In [9]:
A=np.array([[3.,1.,-2.],[1.,2.,-5.],[2.,-4.,1.]])
b=np.array([1.1,2,-3])

row_echelon(A,b)

array([[ 3.        ,  1.        , -2.        ,  1.1       ],
       [ 0.        ,  1.66666667, -4.33333333,  1.63333333],
       [ 0.        ,  0.        , -9.8       ,  0.84      ]])

**Problem 4**

In [10]:
def LU_decomposition(A):
  U=np.copy(A)
  L=np.identity(len(A))
  m, n = np.shape(A)
  for i in range(0,n):
    for j in range(i+1,m):
      L[j,i] = U[j,i] / U[i,i]
      U[j, :] = U[j,:] - L[j,i] * U[i,:]
  return L,U # We've included the return values for you, though your function needs to define them correctly.

In [11]:
A=np.array([[3,1,-2],[1.5,2,-5],[2,-4,1]])

LU_decomposition(A)

(array([[ 1.        ,  0.        ,  0.        ],
        [ 0.5       ,  1.        ,  0.        ],
        [ 0.66666667, -3.11111111,  1.        ]]),
 array([[  3.        ,   1.        ,  -2.        ],
        [  0.        ,   1.5       ,  -4.        ],
        [  0.        ,   0.        , -10.11111111]]))

**Problem 5**

In [12]:
def forward_substitution(L,b): # Accepts a lower triangular square matrix L and a vector b, solves Ly=b for y.
  n = len(b)
  y = np.zeros(n)
  for i in range(0,n):
    y[i] = (b[i] - np.dot(y, L[i,:])) / L[i,i]
  return y

In [13]:
L=np.array([[1,0,0],[3,1,0],[-1.1,2,1]])
b=np.array([-2.1,1,-1])

forward_substitution(L,b)

array([ -2.1 ,   7.3 , -17.91])

**Problem 6**

In [14]:
def back_substitution(U,y):    # Accepts an upper triangular square matrix U and a vector b, solves Ux=b for x.
  n = len(y)
  x = np.zeros(n)
  for i in range(n-1,-1,-1):
    x[i] = (y[i] - np.dot(x, U[i,:])) / U[i,i]
  return x

In [15]:
U=np.array([[2,-3.1,1],[0,1,3],[0,0,4]])
y=np.array([1,-2.1,3])

back_substitution(U,y)

array([-6.6175, -4.35  ,  0.75  ])

**Problem 7**

In [16]:
def LU_solver(A,b): 
  L, U = LU_decomposition(A)
  y = forward_substitution(L, b)
  return back_substitution(U, y)

In [17]:
A=np.array([[3,1,-2],[1.5,2,-5],[2,-4,1]])
b=np.array([1.1,3,-2])

LU_solver(A,b)

array([-0.07032967,  0.34395604, -0.48351648])

**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.   

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file. In the "File" menu select "Download .py". The resulting file can then be uploaded to http://www.math.byu.edu:30000 for grading.